version: "3.8"

networks:
  app:
    driver: bridge

services:
  example:
    build:
      context: .
      dockerfile: build/Dockerfile
    volumes:
      - .:/app
    networks:
      - app
    ports:
      - 8080:8080