[webserver]
header = "Fiber"
app_name = "Fiber"
port = ":8080"
prefork = true
production = false

[logger]
time-format = "" # https://pkg.go.dev/time#pkg-constants, https://github.com/rs/zerolog/blob/master/api.go#L10 
level = 0 # panic -> 5, fatal -> 4, error -> 3, warn -> 2, info -> 1, debug -> 0, trace -> -1
prettier = true

[limiter]
enabled = false
max = 20
expiration_seconds = 60

[session]
enabled = true
expiration_hours = 24

[compress]
enabled = true
level = 2

[recover]
enabled = true

[monitor]
enabled = true

[filesystem]
enabled = true
browse = true
max_age = 3600
index = "index.html"
root = "./storage/public"